# Generated by Django 5.0.6 on 2026-07-25 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REC', 'Receita'), ('DES', 'Despesa')], max_length=3)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_prevista', models.DateField()),
                ('realizado', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos', to='financeiro.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos', to='financeiro.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_prevista'],
            },
        ),
    ]
