# Generated by Django 5.0.6 on 2026-07-25 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_planejamentofinanceiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planejamentofinanceiro',
            options={'ordering': ['data_prevista', 'descricao']},
        ),
        migrations.RenameField(
            model_name='planejamentofinanceiro',
            old_name='realizado',
            new_name='parcelado',
        ),
        migrations.RemoveField(
            model_name='planejamentofinanceiro',
            name='observacao',
        ),
        migrations.AddField(
            model_name='planejamentofinanceiro',
            name='parcela_atual',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planejamentofinanceiro',
            name='prioridade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alta'), (2, 'Média'), (3, 'Baixa')], default=3),
        ),
        migrations.AddField(
            model_name='planejamentofinanceiro',
            name='recorrencia',
            field=models.CharField(choices=[('NEN', 'Nenhuma'), ('DIA', 'Diária'), ('SEM', 'Semanal'), ('MEN', 'Mensal'), ('ANU', 'Anual')], default='NEN', max_length=3),
        ),
        migrations.AddField(
            model_name='planejamentofinanceiro',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('PAG', 'Pago'), ('CAN', 'Cancelado')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='planejamentofinanceiro',
            name='total_parcelas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='planejamentofinanceiro',
            constraint=models.UniqueConstraint(fields=('usuario', 'descricao', 'data_prevista'), name='planejamento_unico_usuario'),
        ),
    ]
