# Generated by Django 5.0.6 on 2026-07-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_planejamentofinanceiro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentofinanceiro',
            name='movimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamento', to='financeiro.movimento'),
        ),
    ]
