# Generated by Django 5.0.6 on 2026-07-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_planejamentofinanceiro_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentofinanceiro',
            name='recorrencia',
            field=models.CharField(choices=[('NEN', 'Nenhuma'), ('DIA', 'Diária'), ('SEM', 'Semanal'), ('MEN', 'Mensal'), ('ANU', 'Anual'), ('QUI', 'Quinzenal')], default='NEN', max_length=3),
        ),
    ]
