# Generated by Django 5.0.6 on 2026-07-25 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_planejamentofinanceiro_recorrencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planejamentofinanceiro',
            name='planejamento_unico_usuario',
        ),
        migrations.AddConstraint(
            model_name='planejamentofinanceiro',
            constraint=models.UniqueConstraint(fields=('usuario', 'descricao', 'tipo', 'data_prevista'), name='planejamento_unico_usuario'),
        ),
    ]
