# Generated by Django 5.0.6 on 2026-07-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_remove_planejamentofinanceiro_planejamento_unico_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentofinanceiro',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
